### ISSUE TITLE
Making jetpack compose port? 

### ISSUE THREAD

**Issue by moumn-almunawy** [xenodium/ob-swiftui#2]
Hi, I just want to ask about the possibility of making something similar but for jetpack compose

**Comment by xenodium** [comment]
Thanks for the interest but I haven't got experience with Jetpack Compose.

The way ob-swiftui works is fairly straightforward. It generates a small but complete macOS app snippet. The snippet is fed to the swift compiler to build/run. The macOS app takes a screenshot of the window/view, saves it to an images on disk, prints the path, and exits. The printed path is used to render the image in Emacs. 

If you build the Kotlin snippet, I can try to give pointers with the elisp integration, though maybe check the source here. The general logic may be reusable. 

I'll close this feature request as its out of scope and I haven't got the relevant experience. 

Please feel free to reach out if you have questions. Happy to share whatever knowledge I have.
